### ISSUE TITLE
update to 1.0.1 from 1.0.0 causes AR 2.3.11 loading problems

### ISSUE THREAD

**Issue by obrie** [pluginaweek/state_machine#91]
**Aaron Gibralter** opened this issue

I upgraded to 1.0.1 from 1.0.0 and whenever I try to load my app environment I get this typoe of error:

Expected /.../myapp/app/models/user/extras.rb to define User::Extras

where user.rb has `include User::Extras` in it and my environment.rb has:

```
Rails::Initializer.run do |config|
  # Add model subdirectories.
  config.autoload_paths += Dir[
    File.join(Rails.root, &rsquo;app&rsquo;, &rsquo;models&rsquo;, &rsquo;**&rsquo;)
  ].reject{ |f| !File.directory?(f) }
end
```

Any thoughts on why this may be happening now?

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13288/tickets/81)

 This ticket has 0 attachment(s).

**Comment by obrie** [comment]
Hmm, that&rsquo;s interesting.  Sorry to have caused the regression!  I&rsquo;m not entirely sure what could have caused it off the top of my head.  There were a few changes made to scopes and defining helper methods that could potentially be related.  In addition, I did also make a change to how the locale paths got defined in Rails 2.x integrations.

I&rsquo;ll definitely be sure to take a look as soon as I can tonight.  If you have any other information about the state machine, stack trace, ruby version, etc., that would be great!

**Comment by obrie** [comment]
**Aaron Gibralter** commented

Here is a trace, though it contains no mention of state_machine... I just know that when I downgrade to 1.0.0, it works.

$ rake spec --trace
rake/rdoctask is deprecated.  Use rdoc/task instead (in RDoc 2.4.2+)
*\* Invoke spec (first_time)
*\* Invoke db:test:load (first_time)
*\* Invoke db:test:purge (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
Expected /Users/me/myapp/app/models/membership/serialization.rb to define Membership::Serialization
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:452:in `load_missing_constant&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:122:in`const_missing&rsquo;
/Users/me/myapp/app/models/membership.rb:38
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:406:in `load_without_new_constant_marking&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:406:in`load_file&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:547:in `new_constants_in&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:405:in`load_file&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:285:in `require_or_load&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:451:in`load_missing_constant&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:106:in `const_missing&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:118:in`const_missing&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/inflector.rb:364:in `constantize&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/inflector.rb:363:in`each&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/inflector.rb:363:in `constantize&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/core_ext/string/inflections.rb:162:in`constantize&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activerecord-2.3.11/lib/active_record/observer.rb:157:in `observed_class&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activerecord-2.3.11/lib/active_record/observer.rb:183:in`observed_classes&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activerecord-2.3.11/lib/active_record/observer.rb:166:in `initialize&rsquo;
/Users/me/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/singleton.rb:94:in`new&rsquo;
/Users/me/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/singleton.rb:94:in `instance&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activerecord-2.3.11/lib/active_record/observer.rb:38:in`instantiate_observers&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activerecord-2.3.11/lib/active_record/observer.rb:36:in `each&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activerecord-2.3.11/lib/active_record/observer.rb:36:in`instantiate_observers&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/actionpack-2.3.11/lib/action_controller/dispatcher.rb:15:in `define_dispatcher_callbacks&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/callbacks.rb:182:in`call&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/callbacks.rb:182:in `evaluate_method&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/callbacks.rb:166:in`call&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/callbacks.rb:90:in `run&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/callbacks.rb:90:in`each&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/callbacks.rb:90:in `send&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/callbacks.rb:90:in`run&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/callbacks.rb:276:in `run_callbacks&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/actionpack-2.3.11/lib/action_controller/dispatcher.rb:51:in`send&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/actionpack-2.3.11/lib/action_controller/dispatcher.rb:51:in `run_prepare_callbacks&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rails-2.3.11/lib/initializer.rb:631:in`prepare_dispatcher&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rails-2.3.11/lib/initializer.rb:185:in `process&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rails-2.3.11/lib/initializer.rb:113:in`send&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rails-2.3.11/lib/initializer.rb:113:in `run&rsquo;
/Users/me/myapp/config/environment.rb:6
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in`require&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in `require&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:547:in`new_constants_in&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in `require&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rails-2.3.11/lib/tasks/misc.rake:4
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:205:in`call&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:205:in `execute&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:200:in`each&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:200:in `execute&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:158:in`invoke_with_call_chain&rsquo;
/Users/me/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/monitor.rb:242:in `synchronize&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:151:in`invoke_with_call_chain&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:176:in `invoke_prerequisites&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:174:in`each&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:174:in `invoke_prerequisites&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:157:in`invoke_with_call_chain&rsquo;
/Users/me/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/monitor.rb:242:in `synchronize&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:151:in`invoke_with_call_chain&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:176:in `invoke_prerequisites&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:174:in`each&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:174:in `invoke_prerequisites&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:157:in`invoke_with_call_chain&rsquo;
/Users/me/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/monitor.rb:242:in `synchronize&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:151:in`invoke_with_call_chain&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:176:in `invoke_prerequisites&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:174:in`each&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:174:in `invoke_prerequisites&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:157:in`invoke_with_call_chain&rsquo;
/Users/me/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/monitor.rb:242:in `synchronize&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:151:in`invoke_with_call_chain&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:144:in `invoke&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/application.rb:112:in`invoke_task&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/application.rb:90:in `top_level&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/application.rb:90:in`each&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/application.rb:90:in `top_level&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/application.rb:129:in`standard_exception_handling&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/application.rb:84:in `top_level&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/application.rb:62:in`run&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/application.rb:129:in `standard_exception_handling&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/application.rb:59:in`run&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/bin/rake:31
/Users/me/.rvm/gems/ree-1.8.7-2011.03/bin/rake:19:in `load&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/bin/rake:19
Tasks: TOP => spec => db:test:load => db:test:purge => environment

**Comment by obrie** [comment]
**Aaron Gibralter** commented

Dammit, that got mangled...

```
$ rake spec --trace
rake/rdoctask is deprecated.  Use rdoc/task instead (in RDoc 2.4.2+)
** Invoke spec (first_time)
** Invoke db:test:load (first_time)
** Invoke db:test:purge (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
Expected /Users/me/myapp/app/models/membership/serialization.rb to define Membership::Serialization
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:452:in `load_missing_constant&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:122:in `const_missing&rsquo;
/Users/me/myapp/app/models/membership.rb:38
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:406:in `load_without_new_constant_marking&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:406:in `load_file&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:547:in `new_constants_in&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:405:in `load_file&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:285:in `require_or_load&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:451:in `load_missing_constant&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:106:in `const_missing&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:118:in `const_missing&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/inflector.rb:364:in `constantize&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/inflector.rb:363:in `each&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/inflector.rb:363:in `constantize&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/core_ext/string/inflections.rb:162:in `constantize&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activerecord-2.3.11/lib/active_record/observer.rb:157:in `observed_class&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activerecord-2.3.11/lib/active_record/observer.rb:183:in `observed_classes&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activerecord-2.3.11/lib/active_record/observer.rb:166:in `initialize&rsquo;
/Users/me/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/singleton.rb:94:in `new&rsquo;
/Users/me/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/singleton.rb:94:in `instance&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activerecord-2.3.11/lib/active_record/observer.rb:38:in `instantiate_observers&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activerecord-2.3.11/lib/active_record/observer.rb:36:in `each&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activerecord-2.3.11/lib/active_record/observer.rb:36:in `instantiate_observers&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/actionpack-2.3.11/lib/action_controller/dispatcher.rb:15:in `define_dispatcher_callbacks&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/callbacks.rb:182:in `call&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/callbacks.rb:182:in `evaluate_method&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/callbacks.rb:166:in `call&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/callbacks.rb:90:in `run&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/callbacks.rb:90:in `each&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/callbacks.rb:90:in `send&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/callbacks.rb:90:in `run&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/callbacks.rb:276:in `run_callbacks&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/actionpack-2.3.11/lib/action_controller/dispatcher.rb:51:in `send&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/actionpack-2.3.11/lib/action_controller/dispatcher.rb:51:in `run_prepare_callbacks&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rails-2.3.11/lib/initializer.rb:631:in `prepare_dispatcher&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rails-2.3.11/lib/initializer.rb:185:in `process&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rails-2.3.11/lib/initializer.rb:113:in `send&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rails-2.3.11/lib/initializer.rb:113:in `run&rsquo;
/Users/me/myapp/config/environment.rb:6
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in `require&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in `require&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:547:in `new_constants_in&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in `require&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rails-2.3.11/lib/tasks/misc.rake:4
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:205:in `call&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:205:in `execute&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:200:in `each&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:200:in `execute&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:158:in `invoke_with_call_chain&rsquo;
/Users/me/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/monitor.rb:242:in `synchronize&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:151:in `invoke_with_call_chain&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:176:in `invoke_prerequisites&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:174:in `each&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:174:in `invoke_prerequisites&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:157:in `invoke_with_call_chain&rsquo;
/Users/me/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/monitor.rb:242:in `synchronize&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:151:in `invoke_with_call_chain&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:176:in `invoke_prerequisites&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:174:in `each&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:174:in `invoke_prerequisites&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:157:in `invoke_with_call_chain&rsquo;
/Users/me/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/monitor.rb:242:in `synchronize&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:151:in `invoke_with_call_chain&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:176:in `invoke_prerequisites&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:174:in `each&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:174:in `invoke_prerequisites&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:157:in `invoke_with_call_chain&rsquo;
/Users/me/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/monitor.rb:242:in `synchronize&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:151:in `invoke_with_call_chain&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/task.rb:144:in `invoke&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/application.rb:112:in `invoke_task&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/application.rb:90:in `top_level&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/application.rb:90:in `each&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/application.rb:90:in `top_level&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/application.rb:129:in `standard_exception_handling&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/application.rb:84:in `top_level&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/application.rb:62:in `run&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/application.rb:129:in `standard_exception_handling&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/lib/rake/application.rb:59:in `run&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/gems/rake-0.9.0/bin/rake:31
/Users/me/.rvm/gems/ree-1.8.7-2011.03/bin/rake:19:in `load&rsquo;
/Users/me/.rvm/gems/ree-1.8.7-2011.03/bin/rake:19
Tasks: TOP => spec => db:test:load => db:test:purge => environment
```

**Comment by obrie** [comment]
Hey Aaron -

I have a suspicion regarding what the issue is, but I can&rsquo;t say for certain without a little more understanding of how User and User::Extras interact with each other.  Let&rsquo;s start with my guess: there seems to be a circular reference between User and User::Extras which causes the error.  You could simulate it with the following files:

user.rb
 @@@ ruby
class User
  include User::Extras
end
 @@@

user/extras.rb
 @@@ ruby
User.class eval do
  module Extras
  end
end
 @@@

Now there was this change - https://github.com/pluginaweek/state_machine/commit/a58f5ee1cf21be469ced9c07bb231b0d1db8f64c - which could have caused the issue you&rsquo;re seeing.  Unfortunately, I haven&rsquo;t been able to come up with an example scenario where it happens.

If there&rsquo;s any chance you could provide more info about these files or perhaps chat on IRC about it, that&rsquo;d be great.  I definitely want to get this issue resolved asap.

**Comment by obrie** [comment]
Hm it actually appears as though my example may have been a bit invalid since user/extras.rb wouldn&rsquo;t actually end up defining User::Extras.  Either way, I feel like the changeset I referenced is somehow causing this issue.

**Comment by obrie** [comment]
**Aaron Gibralter** commented

Where can I find you on IRC?

**Comment by obrie** [comment]
**Aaron Gibralter** commented

I have:

app/models/user.rb:

```
class User
  include User::Extras
end
```

app/models/user/extras.rb:

```
module User::Extras
  def foo
  end
end
```

Kind of like a soft-core https://github.com/jakehow/concerned_with...

**Comment by obrie** [comment]
@agibralter Can you try running against the latest changes in master and seeing if this makes a difference with the issue you were seeing?  I haven't heard from anyone else experiencing this and I'm hoping some of the AR-related issues that have been fixed since 1.0.1 resolve the problem.

**Comment by obrie** [comment]
The other suggestion I might have is to try the following:

``` ruby
StateMachine::Machine.ignore_method_conflicts = true
```

This will prevent state_machine from walking the ancestor hierarchy in order to detect method conflicts.

**Comment by agibralter** [comment]
@obrie -- Awesome! The master branch of state_machine works now. I tried 1.0.1 again just to make sure that it still does not work with my code base, and, as expected, 1.0.1 did not work.

Thank you! Is 1.0.2 close to release?

**Comment by obrie** [comment]
That's great!  1.0.2 was actually released last night, so you're all set on that front :)

**Comment by agibralter** [comment]
thanks! :)
